version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: just-in-time
      POSTGRES_USER: root
      POSTGRES_PASSWORD:  123
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local